# Generated by Django 3.1.7 on 2021-05-23 16:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN_ID_Number', models.CharField(max_length=10, null=True)),
                ('Adhar_Card_Number', models.CharField(max_length=16, null=True)),
                ('Mobile_Number', models.CharField(max_length=10, null=True)),
                ('Photo', models.FileField(blank=True, upload_to='UserImage/')),
                ('Update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Category_M', models.CharField(max_length=100, null=True)),
                ('Title_M', models.CharField(max_length=200, null=True)),
                ('Details_M', ckeditor.fields.RichTextField(null=True)),
                ('ImagesM', models.FileField(blank=True, upload_to='images/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Likes_M', models.ManyToManyField(related_name='blog_Post', to=settings.AUTH_USER_MODEL)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Google_Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compeny_Name', models.CharField(max_length=200, null=True)),
                ('ADD', models.FileField(blank=True, upload_to='Google_ADDs/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Clicking', models.ManyToManyField(related_name='clicking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(max_length=200, null=True)),
                ('Commented_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BlogAPP.instruction')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Category_Field', models.CharField(max_length=200, null=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Admin_Name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
