# Generated by Django 3.1.7 on 2021-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0005_auto_20210525_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='Facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_information',
            name='First_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_information',
            name='Instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user_information',
            name='Last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
