# Generated by Django 3.1.7 on 2021-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0007_auto_20210526_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='Liked_int_M',
            field=models.IntegerField(default='0'),
        ),
    ]
