# Generated by Django 3.1.7 on 2021-05-27 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogAPP', '0008_auto_20210527_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='Likes_M',
            field=models.ManyToManyField(blank=True, related_name='blog_Post', to=settings.AUTH_USER_MODEL),
        ),
    ]
