# Generated by Django 3.1.7 on 2021-05-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0009_auto_20210528_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='LindedIN',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
