# Generated by Django 3.1.7 on 2021-05-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogAPP', '0012_auto_20210528_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADD', models.FileField(blank=True, upload_to='Google_ADDs/')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Clicking', models.ManyToManyField(related_name='clicking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Google_Add',
        ),
    ]
