# Generated by Django 3.1.7 on 2021-05-28 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogAPP', '0013_auto_20210528_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadd',
            name='Company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='googleadd',
            name='Clicking',
            field=models.ManyToManyField(blank=True, related_name='clicking', to=settings.AUTH_USER_MODEL),
        ),
    ]
