# Generated by Django 3.1.7 on 2021-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0015_googleadd_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleadd',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
