# Generated by Django 3.1.7 on 2021-05-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAPP', '0016_auto_20210528_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleadd',
            name='Company_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
